Bump to 23.3.0.
conda-forge/conda-libmamba-solver-feedstock pull request #12
Opened 2023-03-31 14:04 UTC by jezdez

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2023-03-31 14:06 UTC, jezdez commented
@conda-forge-admin, please rerender

2023-03-31 14:33 UTC, jaimergp commented on recipe/meta.yaml
>    url: https://github.com/conda/conda-libmamba-solver/archive/{{ version }}.tar.gz  # temporary
```suggestion
  url: https://github.com/conda/conda-libmamba-solver/archive/{{ version }}.tar.gz
```

I don't know what was temporary but the current URL doesn't look like it :D

2023-03-31 15:57 UTC, jaimergp requested changes
Leaving this here because we won't ship til Monday to have a calm weekend 🏖️ 🙏

2023-04-03 07:54 UTC, jaimergp approved these changes

2023-04-03 07:55 UTC, jaimergp commented
Let's do this.

2023-04-03 07:56 UTC, merged